# Generated by Django 5.2.7 on 2025-11-01 09:28

import air_zone.extra_scripts.get_image_path_for_db_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rows', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('image', models.ImageField(upload_to=air_zone.extra_scripts.get_image_path_for_db_model.get_image_path_for_db_model)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('carrying', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airplane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='air_zone.airplane')),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='air_zone.crew')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.route')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='air_zone.typereference')),
            ],
        ),
    ]
