# Generated by Django 5.2.7 on 2025-11-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_zone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typereference',
            old_name='mass',
            new_name='masa',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type_reference',
        ),
        migrations.AddField(
            model_name='airplane',
            name='references',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='air_zone.typereference'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='air_zone.type'),
        ),
    ]
