# Generated by Django 5.2.7 on 2025-11-04 12:06

import air_zone.extra_scripts.get_image_path_for_db_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_zone', '0002_rename_mass_typereference_masa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, upload_to=air_zone.extra_scripts.get_image_path_for_db_model.get_image_path_for_db_model),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='crew',
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(null=True, to='air_zone.crew'),
        ),
    ]
