# Generated by Django 5.2.7 on 2025-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0003_alter_airport_name_airport_unique_airport"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="travel_date",
            field=models.DateTimeField(null=True),
        ),
    ]
